version: 0.2

env:
  variables:
    S3_BUCKET: adv-glasswall-fe-public
    S3_PREFIX: GlassWall-DEV
    S3_BUCKET_BE: glasswall-codebuild
    S3_BUCKET_BE_PREFIX: be
    GLASSWALL_REGIN: cn-northwest-1

phases: 

  install:
    runtime-versions:
        nodejs: 12
    commands:
      # Install all dependencies (including dependencies for running tests)
      - cd glasswall-fe
      - npm install
      - cd ..

  pre_build:
    commands:
      # Discover and run unit tests in the '__tests__' directory
      - cd glasswall-fe
      # - npm run test
      # Remove all dependencies not needed for the Lambda deployment package (the packages from devDependencies in package.json)
      - npm prune --production      
      - echo "PRE BUILD2"
      - cd ..

  build: 
    commands:
      - echo Building the frontend code...
      - echo $CODEBUILD_SRC_DIR
      - cd $CODEBUILD_SRC_DIR/glasswall-fe
      - npm run build
      - set | sort
      - cd ..

      - echo Building the backend-js code...
      - echo $CODEBUILD_SRC_DIR
      - cd $CODEBUILD_SRC_DIR/glasswall-be-js
      - sam build
      - if [ $? -ne 0 ]; then echo "error, sam build"; exit 10; fi
      - sam package --template-file template.yaml --s3-bucket $S3_BUCKET_BE --s3-prefix $S3_BUCKET_BE_PREFIX --region $GLASSWALL_REGIN --output-template-file packaged-template-be-js.yaml
      - if [ $? -ne 0 ]; then echo "error, sam package"; exit 10; fi
      - aws s3 ls $S3_BUCKET_BE/$S3_BUCKET_BE_PREFIX
      - cd ..

  post_build:
    commands:
      - cd glasswall-fe
      - aws s3 ls 
      - aws s3 sync build/ s3://$S3_BUCKET --acl public-read
      #- aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml
      - echo "POST BUILD DONE `date` "
      - cd ..

artifacts:
  secondary-artifacts:
    nodejs_be_js_artifacts:
      base-directory: glasswall-be-js
      files:
        - packaged-template-be-js.yaml
    nodejs_fe_artifacts:
      base-directory: glasswall-fe
      type: zip
      files:
        - packaged-template-be-js.yaml
    
