AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  A simple backend (read/write to DynamoDB) with a RESTful API endpoint using
  Amazon API Gateway.
Resources:
  lijingMicroServiceJS:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: .
      Description: >-
        A simple backend (read/write to DynamoDB) with a RESTful API endpoint
        using Amazon API Gateway.
      MemorySize: 512
      Timeout: 10
      Role: 'arn:aws:iam::359221844733:role/glasswall-be-dev-eu-central-1-lambdaRole'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /lijingMicroServiceJS
            Method: ANY
      Tags:
        'lambda-console:blueprint': microservice-http-endpoint
