AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  A simple backend (read/write to DynamoDB) with a RESTful API endpoint using
  Amazon API Gateway.
Resources:
  glasswallFunJs:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      AutoPublishAlias: live
      DeploymentPreference:
        Type: Linear10PercentEvery1Minute
      CodeUri: .
      Description: >-
        glasswall backend (read/write to DynamoDB) with a RESTful API endpoint
        using Amazon API Gateway.
      MemorySize: 512
      Timeout: 10
      Role: 'arn:aws-cn:iam::814049249523:role/glasswall-lambda-role'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /glasswall-be-js-api
            Method: ANY
